### ISSUE TITLE
Init.d

### ISSUE THREAD

**Issue by NicholasBM** [mmornati/ruby-noise-detection#5]
Tried to get the script to run at startup, did you ever get this running via init d? If so a few pointers would be really helpful.

**Comment by mmornati** [comment]
Yes sure. The configuration within the repository was for `init.d`. The script is quite old now but I can try to help you. What is your problem?

**Comment by NicholasBM** [comment]
So I checked out the script in the init.d and made sure any files it referenced were in place and moved it to my init.d folder set it up to boot on start etc ran the commands to make it executable and sudo update-rc.d.

If I just try n test it by starting service noised. I get nothing as if it's worked, but not getting alerts etc as it does when running via terminal. But if I check the status u get. 

Loaded: Loaded  
Active: active (exited)
Docs: man:systemd-sysv-generator
Process: 3494 Exestart=/etc/init.d/noised start (code=exited, status=0/SUCCESS

Starting LSB: Start Daemon at boot time...
1
/Etc/init.d/noised: 45 /etc/init.d/noised: status: not found
Starting noise detector
Starting LSB: Start Daemon at boot time
Daemon: client PID exited with 1 status

**Comment by mmornati** [comment]
And is there anything in your `/var/log/messages` (or `/var/log/boot.log` or whatever) to help to identify why the script is not starting?
It can be something related to the start order: you want to access to the USB camera/micro but they are not ready at the moment the init.d script is running.

**Comment by NicholasBM** [comment]
Checked those files and no sign of anything related to my service in boot, which makes me think it's not getting started. Can't see anything obvious in messages.

If I try just to run the script instead of start the service so, sudo /etc/init.d/noised start I get

1
/etc/init.d/noised: 45 /etc/init.d/noised: status not found
Starting noise detector: /etc/init.d/noised: 53 /etc/init.d/noised: rh_status_q: not found

Then if I do the same but status, I get

/etc/init.d/noised: 45 /etc/init.d/noised: status not found

/etc/init.d/noised:86 /etc/init.d/noised status not found

**Comment by NicholasBM** [comment]
Also noticed that if I run the script there is no PID file created in the same local as if I run the .RB file at terminal. Unless the script puts the PID somewhere else

**Comment by NicholasBM** [comment]
Just wanted to say that I got the script working on start up by putting the command in rc.local so didnt use the initd stuff. I just got the following to run on startup

/usr/local/bin/ruby /home/pi/noise_detection.rb -m 1 -n 0.30 -v &

I have edited the script to call a webhook instead of emailing so it triggers an alert. Thanks for your effort and for the cool application it is working perfectly now :-)
